# Automatically generated by scripts/boost/generate-ports.ps1

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO boostorg/cobalt
    REF boost-${VERSION}
    SHA512 fa280b607729f6f0cb9af77bbf9d5aae9add62474ff7916f0a9738a1ada527fecf050f85dd193912373133c813e4421e571e12ecde1085be1824fb25f3512073
    HEAD_REF master
    PATCHES
        fail-on-compiler-not-supported.patch
)

# JD: hack to make compilation work on epel8 distros
if (CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    execute_process(
        COMMAND cat /etc/os-release
        OUTPUT_VARIABLE OS_RELEASE_CONTENT
    )

    string(REGEX MATCH "ID=[\"']?almalinux[\"']?" ALMA_MATCH "${OS_RELEASE_CONTENT}")

    if (ALMA_MATCH)
      set(VCPKG_CXX_FLAGS -fcoroutines)
      set(VCPKG_C_FLAGS -fcoroutines)
    endif()
endif()

set(FEATURE_OPTIONS "")
boost_configure_and_install(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS ${FEATURE_OPTIONS}
)
